# Generated by Django 2.2.10 on 2020-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_auto_20200306_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
            ],
        ),
    ]
